-- ========================================================
-- Supabase Schema for Roidstarlabs Clone
-- Copy and run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/ehxhgpgyminvyvebbqlg/sql
-- ========================================================

-- 1. Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  category_slug text,
  price numeric not null,
  rating numeric default 0,
  popularity integer default 0,
  image text,
  hover_image text,
  description text,
  dosage text,
  form text,
  in_stock boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) and public read access
alter table public.products enable row level security;
create policy "Allow public read-only access on products"
  on public.products for select
  using (true);

-- 2. Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null,
  total_amount numeric not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and public insert access for checkout orders
alter table public.orders enable row level security;
create policy "Allow public insert on orders"
  on public.orders for insert
  with check (true);

create policy "Allow authenticated read on orders"
  on public.orders for select
  using (true);
